name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
    
    - name: Install dependencies
      run: cd HSBIS.ReservaMesas && dotnet restore

    - name: Build
      run: cd HSBIS.ReservaMesas && dotnet build
      
    - name: Test
      run: cd HSBIS.ReservaMesas && dotnet test --no-restore --verbosity normal
